// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmrxadjfjvwniueijzso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtcnhhZGpmanZ3bml1ZWlqenNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NDUxMDUsImV4cCI6MjA1OTQyMTEwNX0.4hg2IK2JOG0BQl3VmXp2sgeizPz1SXhoQqzABSHuuoo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);